/*
 * File: app/view/NavMain.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('YemekhaneApp.view.NavMain', {
    extend: 'Ext.navigation.View',
    alias: 'widget.NavMain',

    requires: [
        'YemekhaneApp.view.BtnSettings',
        'YemekhaneApp.view.override.NavMain'
    ],

    config: {
        id: 'NavMain',
        ui: '',
        listeners: [
            {
                fn: 'onMainNavInitialize',
                event: 'initialize'
            },
            {
                fn: 'onBtnSettingsTap',
                event: 'tap',
                delegate: '#btnsettings'
            }
        ],
        navigationBar: {
            docked: 'top',
            id: 'navBar',
            items: [
                {
                    xtype: 'BtnSettings',
                    itemId: 'btnsettings',
                    align: 'right'
                }
            ]
        }
    },

    onMainNavInitialize: function(component, eOpts) {
        //
    },

    onBtnSettingsTap: function(button, e, eOpts) {
        //
    }

});