/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Settings',
        'Yemekhane',
        'GunlukMenu'
    ],
    stores: [
        'StoreSettings',
        'StoreYemekhane',
        'StoreGunlukMenu'
    ],
    views: [
        'NavMain',
        'ListGunlukMenu',
        'MyPanel',
        'ListYemekhane',
        'BtnSettings',
        'PanelSettings'
    ],
    name: 'YemekhaneApp',

    launch: function() {
        //var listGunlukMenu = Ext.getCmp("listGunlukMenu");
        //var listGunlukMenu = Ext.getCmp("mainNav").items[0];
        //listGunlukMenu.setData([{tarih:'12.01.2012',kalori:300}]);

        Ext.create('YemekhaneApp.view.NavMain', {fullscreen: true});
    }

});
